// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FrontendLogService 是供前端调用的 Go 绑定服务：接收前端日志/错误并写入 frontend.log。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";

/**
 * FrontendLog 由前端调用：level 取值 debug/info/warn/error，msg 为日志文本。
 */
export function FrontendLog(level: string, msg: string): $CancellablePromise<void> {
    return $Call.ByID(1142342357, level, msg);
}

/**
 * SetLevel 同步前端日志级别（由 applyLogConfig 调用）。
 */
export function SetLevel(level: slog$0.Level): $CancellablePromise<void> {
    return $Call.ByID(413077503, level);
}
