// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigWrapper 负责 UI 配置（语言/主题/默认引擎/热键/TTS/执行键）的持久化与读取，
 * 以及语言/主题的解析与对外查询。引擎配置（Engines）由 EngineWrapper 独立管理。
 * 仅暴露 RPC，不实现 wails 生命周期三件套。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig 返回当前配置指针。
 */
export function GetConfig(): $CancellablePromise<settings$0.Settings | null> {
    return $Call.ByID(651119548);
}

/**
 * GetLanguages 返回支持的语言 (value=code, name=展示名)。
 */
export function GetLanguages(lang: string): $CancellablePromise<$models.NamedItem[] | null> {
    return $Call.ByID(3807973897, lang);
}

/**
 * GetSystemTheme 返回当前系统外观解析后的实际主题（dark/light）。
 * Wails webview 内的 matchMedia('prefers-color-scheme') 在 macOS 上可能不可靠，
 * 因此由后端通过 application.Env.IsDarkMode() 提供唯一可信来源。
 */
export function GetSystemTheme(): $CancellablePromise<string> {
    return $Call.ByID(1303942916);
}

/**
 * GetTheme 返回当前主题配置（可能含 auto）。
 */
export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(3923435619);
}

/**
 * SaveConfig 持久化 UI 配置到 settings.json；语言/主题变更会全局同步。
 */
export function SaveConfig(cfg: settings$0.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(1150430385, cfg);
}

/**
 * SetApp 在 app 就绪后注入。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(600301637, app);
}

/**
 * SetTheme 持久化主题配置。
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(995726519, theme);
}

/**
 * SystemLanguages 返回 macOS 系统翻译（Translation.framework）已安装的语言包列表。
 * 仅 darwin 可用；非 darwin 平台见 apple_langs_other.go。
 */
export function SystemLanguages(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2181419198);
}

/**
 * Theme 返回用户配置的主题（auto/light/dark，未配置回退 auto）。
 */
export function Theme(): $CancellablePromise<string> {
    return $Call.ByID(1167934511);
}
