// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineWrapper 引擎配置的薄适配层：持有 registry + configstore + settings + hotkey，
 * 负责引擎启停的运行时注册与持久化、schema 下发。仅暴露 RPC，不实现 wails 生命周期三件套。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddEngine 新增单个引擎配置到 config.db，返回 DB 分配的 ID。
 */
export function AddEngine(cfg: engine$0.EngineConfig | null): $CancellablePromise<number> {
    return $Call.ByID(2510416615, cfg);
}

/**
 * CheckTesseract 探测本机是否已安装 tesseract，返回安装状态与可执行路径，
 * 供设置页展示 Tesseract 引擎的「已安装/未安装」提示。
 */
export function CheckTesseract(): $CancellablePromise<engine$0.TesseractStatus> {
    return $Call.ByID(2067219980);
}

/**
 * GetAllEngines 返回 config.db 的 engines 表中「全部」引擎及其启用状态。
 * 列表数据直接来自数据库（configStore.LoadEngines），不经由 settings 副本、也不与
 * 代码里的 KnownEngines 合并——引擎配置是 config.db 的独立数据源，与界面偏好 settings 无关。
 * 新增/启用/删除均通过 form 与各自的 DB 操作完成。
 * kind 取自 KnownEngines 目录（引擎类型由代码注册，不在数据库内）。
 */
export function GetAllEngines(): $CancellablePromise<$models.AllEngineItem[] | null> {
    return $Call.ByID(191559056);
}

/**
 * GetEngineConfig 按 ID 返回单个引擎的完整配置（含已持久化的 api_key/endpoint 等），
 * 供设置页右列表单回填已存值。未找到返回 nil。
 */
export function GetEngineConfig(id: number): $CancellablePromise<engine$0.EngineConfig | null> {
    return $Call.ByID(250220986, id);
}

/**
 * GetEngineSchema 返回指定引擎的「真实」配置字段 schema，供前端动态渲染右列表单。
 */
export function GetEngineSchema(engineName: string): $CancellablePromise<engine$0.EngineSchema> {
    return $Call.ByID(3136113511, engineName);
}

/**
 * GetEngines 返回所有已注册引擎（翻译 + OCR）的 (value, 类型名, 类型) 列表，
 * 顺序严格按 config.db 的 engines 表自增 id 顺序（而非代码注册目录顺序）。
 */
export function GetEngines(): $CancellablePromise<$models.EngineListItem[] | null> {
    return $Call.ByID(1488128365);
}

/**
 * GetKnownEngines 返回「可添加」的引擎目录（来自代码 KnownEngines），
 * 供设置页新增表单的「引擎类型」下拉使用。列表只渲染数据库已有项，
 * 下拉项必须来自代码目录以保证 name 能被 Registry 识别、翻译可工作。
 */
export function GetKnownEngines(): $CancellablePromise<$models.EngineListItem[] | null> {
    return $Call.ByID(1073135640);
}

/**
 * GetOcrLangs 返回 OCR 引擎（vision / tesseract）语言码候选项，
 * 供前端 OCR 专属 UI 渲染 langs 多选。与 Extra(JSON) 解耦，由代码唯一维护。
 */
export function GetOcrLangs(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3491230379);
}

/**
 * RemoveEngine 按 ID 删除单个引擎配置。
 * 系统内置引擎（apple / vision）禁止删除：它们免配置、由代码保证存在，
 * 删除会导致 OCR 单选 / 系统翻译不可用。前端已对 builtin 项隐藏删除按钮，
 * 此处再加后端兜底拦截，避免其它调用途径误删。
 */
export function RemoveEngine(id: number): $CancellablePromise<void> {
    return $Call.ByID(1575958516, id);
}

/**
 * SetApp 在 app 就绪后注入。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(248546961, app);
}

/**
 * ToggleEngineEnabled 按 ID 切换单个引擎的启用/禁用状态。
 * 启用（enabled=true）时校验必填参数，缺项则拒绝开启并提示。
 */
export function ToggleEngineEnabled(id: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1976956865, id, enabled);
}

/**
 * UpdateEngineConfig 按 ID 更新单个引擎的全部配置字段。
 */
export function UpdateEngineConfig(cfg: engine$0.EngineConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3464143975, cfg);
}
