// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryWrapper 翻译历史的薄适配层：持有 historystore.Store + configstore，仅做 RPC 透传与 DTO 转换。
 * 不实现 wails 生命周期三件套。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory 清空历史。
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(2073293877);
}

/**
 * CountHistory 返回符合关键词的历史总条数，供前端分页计算总页数。
 */
export function CountHistory(keyword: string): $CancellablePromise<number> {
    return $Call.ByID(534557787, keyword);
}

/**
 * DeleteHistory 删除一条历史。
 */
export function DeleteHistory(id: number): $CancellablePromise<void> {
    return $Call.ByID(3674865607, id);
}

/**
 * GetHistory 分页查询翻译历史。
 */
export function GetHistory(keyword: string, offset: number, limit: number): $CancellablePromise<$models.HistoryItem[] | null> {
    return $Call.ByID(1672926790, keyword, offset, limit);
}
