// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AllEngineItem 设置页「全部可配置服务」条目（无论是否已启用）
 */
export interface AllEngineItem {
    /**
     * 引擎自增主键 ID
     */
    "id": number;

    /**
     * 引擎标识
     */
    "value": string;

    /**
     * 展示名
     */
    "name": string;

    /**
     * translate | ocr
     */
    "kind": string;

    /**
     * 是否已启用
     */
    "enabled": boolean;

    /**
     * 当前平台是否支持
     */
    "supported": boolean;
}

/**
 * EngineListItem 设置页「引擎」分组：左列服务名、右列配置用。
 * Kind 区分 translate / ocr，前端据此分组并展示不同标记。
 */
export interface EngineListItem {
    /**
     * 引擎标识
     */
    "value": string;

    /**
     * 展示名
     */
    "name": string;

    /**
     * translate | ocr
     */
    "kind": string;

    /**
     * 当前平台是否支持（如 system 仅 darwin）
     */
    "supported": boolean;
}

/**
 * HistoryItem 返回给前端的单条历史（时间转为毫秒时间戳，引擎 ID 转为可读名）。
 */
export interface HistoryItem {
    /**
     * 历史记录自增主键 ID
     */
    "id": number;

    /**
     * 原文
     */
    "text": string;

    /**
     * 翻译结果
     */
    "result": string;

    /**
     * 源语言代码
     */
    "from_lang": string;

    /**
     * 目标语言代码
     */
    "to_lang": string;

    /**
     * 使用的引擎标识
     */
    "engine": string;

    /**
     * 是否来自 OCR 识别结果
     */
    "from_ocr": boolean;

    /**
     * 创建时间（毫秒时间戳）
     */
    "created_at": number;
}

/**
 * NamedItem 带展示名的条目（供前端下拉/列表使用）。
 */
export interface NamedItem {
    /**
     * 选项值（标识）
     */
    "value": string;

    /**
     * 选项展示名
     */
    "name": string;
}
