// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationService 封装原生桌面通知的授权检查与安全发送，
 * 避免调用方直接裸调 Wails notifications service 时漏掉授权判断
 * （macOS 上未授权会静默失败，且无法排查）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifications$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/services/notifications/models.js";

/**
 * Notify 安全发送通知：先确保授权，未授权或被拒则跳过并记录日志，
 * 发送失败也只记日志，绝不向上抛出（更新检查等后台流程不应被通知问题阻断）。
 */
export function Notify(opts: notifications$0.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByID(604523010, opts);
}
