// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TranslateWrapper 翻译 / OCR 的薄适配层：持有 translate.Service，仅做 RPC 透传。
 * 不实现 wails 生命周期三件套（启动编排统一由 AppService 负责）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function Ocr(req: model$0.OcrRequest): $CancellablePromise<model$0.OcrResult | null> {
    return $Call.ByID(1768998496, req);
}

export function ScreenshotOCR(engineName: string): $CancellablePromise<model$0.OcrResult | null> {
    return $Call.ByID(3318430308, engineName);
}

/**
 * ScreenshotTranslate 截图翻译主流程：区域截图→系统 OCR→多引擎翻译→投递到截图窗口。
 * session 标识缓存来源（events.ScreenshotSessionScreenshot / ScreenshotSessionInput）。
 */
export function ScreenshotTranslate(session: string): $CancellablePromise<model$0.ScreenshotResult | null> {
    return $Call.ByID(674436322, session);
}

export function Translate(req: model$0.TranslateRequest): $CancellablePromise<model$0.TranslateResult | null> {
    return $Call.ByID(207873806, req);
}

export function TranslateMulti(req: model$0.TranslateRequest): $CancellablePromise<model$0.TranslateMultiResult | null> {
    return $Call.ByID(2013479831, req);
}
