// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowWrapper 薄适配层：负责各窗口的呼出（主窗口 / 设置窗口）。
 * 窗口句柄由 app 引用按需查询，避免持有过期的 window 实例。
 * 仅暴露前端需要的 RPC，不实现 wails 生命周期三件套。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * SetApp 在 app 就绪后注入。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1570579795, app);
}

/**
 * ShowScreenshotWindow 呼出截图翻译窗口（与 ShowTranslateWindow 对称）。
 * 注：main.go 的 EventWindowShow('screenshot') 当前仍走独立的 showScreenshotWindow()
 * 包级函数；后续可统一迁移到本方法，使窗口呼出全部收口到 WindowWrapper。
 */
export function ShowScreenshotWindow(): $CancellablePromise<void> {
    return $Call.ByID(3066686029);
}

/**
 * ShowSettings 打开设置
 */
export function ShowSettings(): $CancellablePromise<void> {
    return $Call.ByID(2264317276);
}

/**
 * ShowTranslateWindow 呼出翻译窗口
 */
export function ShowTranslateWindow(): $CancellablePromise<void> {
    return $Call.ByID(4045388625);
}
