// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    DNSConfig,
    ExecKeyConfig,
    ExecKeyEntry,
    HotkeyEntry,
    HttpLogConfig,
    LogConfig,
    ProxyConfig,
    RegisteredHotkeyConfig,
    Settings,
    TTSConfig
} from "./models.js";
