// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DNSConfig DNS 解析配置
 */
export interface DNSConfig {
    /**
     * Enabled 是否启用该 DNS 配置。
     */
    "enabled": boolean;

    /**
     * Servers DNS 服务器地址列表。
     */
    "servers": string[] | null;
}

/**
 * ExecKeyConfig 执行类快捷键：程序主动用 robotgo 模拟按下这些键来完成动作，
 * 不参与 mgr.Register 注册（它们是"被按下的键"，不是"被监听的键"）。
 */
export interface ExecKeyConfig {
    /**
     * Copy 复制键：程序模拟按下它完成系统复制（如 macOS Cmd+C）后读剪贴板翻译。
     */
    "copy": ExecKeyEntry;
}

/**
 * ExecKeyEntry 单个执行类快捷键：程序主动模拟按下的键 + 是否启用。
 */
export interface ExecKeyEntry {
    /**
     * Key 程序主动模拟按下的按键组合。
     */
    "key": string;

    /**
     * Enabled 是否启用该执行键。
     */
    "enabled": boolean;

    /**
     * Fallback 模拟复制失败（剪贴板为空 / 注入失败）时，是否回退使用系统默认复制键重试。
     * 开启后：若自定义复制键未生效，自动再用系统原生复制键（macOS Cmd+C / 其他 Ctrl+C）
     * 执行一次，而不是放弃复制。
     */
    "fallback": boolean;
}

/**
 * HotkeyEntry 单个注册类快捷键：既保存按键组合，也保存启用状态。
 * 之前结构只存按键字符串、缺少逐项启用状态；现拆为 Key（按键，空串表示未设置）
 * 与 Enabled（是否启用）。未启用或 Key 为空都不注册。
 */
export interface HotkeyEntry {
    /**
     * Key 按键组合，空串表示未设置。
     */
    "key": string;

    /**
     * Enabled 是否启用该快捷键。
     */
    "enabled": boolean;
}

/**
 * HttpLogConfig HTTP 请求日志配置（暂不同步到前端 UI）。
 */
export interface HttpLogConfig {
    /**
     * Enabled 是否开启 HTTP 请求日志。
     */
    "enabled": boolean;

    /**
     * RetentionDays 日志保留天数。
     */
    "retention_days": number;
}

/**
 * LogConfig 应用运行日志配置（仅写 settings.json，由 main 的日志模块消费，不直接同步前端 UI）。
 * 等级支持 debug / info / warn / error；清理策略基于按天滚动的日志文件。
 */
export interface LogConfig {
    /**
     * Level 日志等级：debug / info / warn / error（空串或非法定值回退 info）。
     */
    "level": string;

    /**
     * RetentionDays 日志文件保留天数（<=0 表示不清理）。
     */
    "retention_days": number;

    /**
     * Compress 是否将过期的旧日志文件压缩为 .gz（保留天数内有效）。
     */
    "compress": boolean;
}

/**
 * ProxyConfig 网络代理配置（暂不同步到前端 UI）。
 */
export interface ProxyConfig {
    /**
     * Enabled 是否启用代理。
     */
    "enabled": boolean;

    /**
     * Protocol 代理协议：http / https / socks5。
     */
    "protocol": string;

    /**
     * Host 代理主机地址。
     */
    "host": string;

    /**
     * Port 代理端口。
     */
    "port": number;

    /**
     * Username 代理认证用户名（可选）。
     */
    "username": string;

    /**
     * Password 代理认证密码（可选）。
     */
    "password": string;
}

/**
 * RegisteredHotkeyConfig 注册类全局快捷键（均通过 mgr.Register 监听，用户按下即触发动作）。
 * 每个快捷键是 HotkeyEntry，含按键与启用状态。
 */
export interface RegisteredHotkeyConfig {
    /**
     * Input 唤起主窗口快捷键（核心功能，默认启用）。
     */
    "input": HotkeyEntry;

    /**
     * Screenshot 截图翻译快捷键。
     */
    "screenshot": HotkeyEntry;
}

/**
 * Settings 应用设置（仅界面偏好，引擎配置在 config.db 独立存储，不在此）。
 */
export interface Settings {
    /**
     * Language 界面语言：auto / zh-CN / en-US（auto 由系统语言解析）。
     * 注意：这是应用界面显示语言，与翻译语言（model.Language：auto/zh/en/...）是两套独立体系，切勿混用。
     */
    "language": string;

    /**
     * Theme 界面主题：auto / light / dark（auto 跟随系统外观）。
     */
    "theme": string;

    /**
     * DefaultTo 翻译默认目标语言（如 zh / en）。
     */
    "default_to": string;

    /**
     * DefaultFrom 翻译默认源语言（auto 表示自动检测）。
     */
    "default_from": string;

    /**
     * Hotkeys 注册类全局快捷键（用户按下即触发动作）。
     */
    "hotkeys": RegisteredHotkeyConfig;

    /**
     * ExecKeys 执行类快捷键（程序主动模拟按下，用于完成动作）。
     */
    "execkeys": ExecKeyConfig;

    /**
     * TTS 语音合成配置。
     */
    "tts": TTSConfig;

    /**
     * HttpLog HTTP 请求日志配置（暂不同步到前端 UI）。
     */
    "http_log": HttpLogConfig;

    /**
     * Log 应用运行日志配置（等级 / 清理 / 压缩）。
     */
    "log": LogConfig;

    /**
     * Proxy 网络代理配置（暂不同步到前端 UI）。
     */
    "proxy": ProxyConfig;

    /**
     * Updater 自动更新配置（仅用户可决策项，token/provider 由代码固定）。
     */
    "updater": UpdaterConfig;

    /**
     * DNSConfigs 自定义 DNS 解析配置列表。
     */
    "dns_configs": DNSConfig[] | null;
}

/**
 * TTSConfig 语音合成配置
 */
export interface TTSConfig {
    /**
     * Engine TTS 引擎标识（如 system）。
     */
    "engine": string;

    /**
     * Speed 语速倍率，1.0 为正常语速。
     */
    "speed": number;
}

/**
 * UpdaterConfig 自动更新相关配置（仅 Prerelease / Source 这类用户可决策项；
 * token / provider / 资源匹配规则由 main.go 代码固定，不在此配置）。
 */
export interface UpdaterConfig {
    /**
     * Prerelease 是否允许检测预发布版（pre-release）更新。
     * 开启后：检查更新时会把 GitHub 仓库的 pre-release 版本也纳入候选。
     */
    "prerelease": boolean;

    /**
     * Source 指定更新检测源：空 / "github" / "cnb"。
     *   - 空（默认）：沿用当前逻辑，按界面语言自动选源（英文走 GitHub，中文走 CNB）。
     *   - "github"：强制只走官方 GitHub（含 SHA256SUMS 校验）。
     *   - "cnb"：强制只走 CNB 镜像（需 cnbToken，匿名 401 / 网络不可达即视为「无更新」）。
     * 注意：仅影响「检测 / 下载源」选择，不影响 updater 自身的安装行为。
     */
    "source": string;
}
