// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package httplogstore

import (
	"time"
)

type HttpLog struct {
	ID                int64     `json:"id"`
	Hostname          *string   `json:"hostname"`
	Method            *string   `json:"method"`
	Url               *string   `json:"url"`
	RequestHeaders    *string   `json:"request_headers"`
	RequestBody       []byte    `json:"request_body"`
	StatusCode        *int64    `json:"status_code"`
	ResponseHeaders   *string   `json:"response_headers"`
	ResponseBody      []byte    `json:"response_body"`
	ElapseTime        *int64    `json:"elapse_time"`
	ProcessElapseTime *int64    `json:"process_elapse_time"`
	IsError           bool      `json:"is_error"`
	CreatedAt         time.Time `json:"created_at"`
	GoVersion         *string   `json:"go_version"`
	PluginVersion     *string   `json:"plugin_version"`
}
