// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package httplogstore

import (
	"context"
	"time"
)

const deleteOldHttpLog = `-- name: DeleteOldHttpLog :execrows
DELETE FROM http_log WHERE created_at < ?
`

func (q *Queries) DeleteOldHttpLog(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldHttpLog, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertHttpLog = `-- name: InsertHttpLog :exec
INSERT INTO http_log (
    hostname, method, url, request_headers, request_body,
    status_code, response_headers, response_body,
    elapse_time, process_elapse_time, is_error, created_at,
    go_version, plugin_version
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertHttpLogParams struct {
	Hostname          *string   `json:"hostname"`
	Method            *string   `json:"method"`
	Url               *string   `json:"url"`
	RequestHeaders    *string   `json:"request_headers"`
	RequestBody       []byte    `json:"request_body"`
	StatusCode        *int64    `json:"status_code"`
	ResponseHeaders   *string   `json:"response_headers"`
	ResponseBody      []byte    `json:"response_body"`
	ElapseTime        *int64    `json:"elapse_time"`
	ProcessElapseTime *int64    `json:"process_elapse_time"`
	IsError           bool      `json:"is_error"`
	CreatedAt         time.Time `json:"created_at"`
	GoVersion         *string   `json:"go_version"`
	PluginVersion     *string   `json:"plugin_version"`
}

func (q *Queries) InsertHttpLog(ctx context.Context, arg InsertHttpLogParams) error {
	_, err := q.db.ExecContext(ctx, insertHttpLog,
		arg.Hostname,
		arg.Method,
		arg.Url,
		arg.RequestHeaders,
		arg.RequestBody,
		arg.StatusCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ElapseTime,
		arg.ProcessElapseTime,
		arg.IsError,
		arg.CreatedAt,
		arg.GoVersion,
		arg.PluginVersion,
	)
	return err
}
