// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package httplogstore

import (
	"context"
	"time"
)

type Querier interface {
	DeleteOldHttpLog(ctx context.Context, createdAt time.Time) (int64, error)
	InsertHttpLog(ctx context.Context, arg InsertHttpLogParams) error
}

var _ Querier = (*Queries)(nil)
