// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package historystore

type History struct {
	ID        int64  `json:"id"`
	Text      string `json:"text"`
	Result    string `json:"result"`
	FromLang  string `json:"from_lang"`
	ToLang    string `json:"to_lang"`
	EngineID  int64  `json:"engine_id"`
	FromOcr   int64  `json:"from_ocr"`
	CreatedAt int64  `json:"created_at"`
}
