// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package historystore

import (
	"context"
)

type Querier interface {
	ClearHistory(ctx context.Context) error
	CountHistory(ctx context.Context, dollar_1 interface{}) (int64, error)
	DeleteHistory(ctx context.Context, id int64) error
	FindDuplicate(ctx context.Context, arg FindDuplicateParams) (int64, error)
	InsertHistory(ctx context.Context, arg InsertHistoryParams) (int64, error)
	QueryHistory(ctx context.Context, arg QueryHistoryParams) ([]History, error)
}

var _ Querier = (*Queries)(nil)
