// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package historystore

import (
	"context"
)

const clearHistory = `-- name: ClearHistory :exec
DELETE FROM history
`

func (q *Queries) ClearHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearHistory)
	return err
}

const countHistory = `-- name: CountHistory :one
SELECT COUNT(*) FROM history
WHERE (?1 = '' OR text LIKE '%' || ?1 || '%' OR result LIKE '%' || ?1 || '%')
`

func (q *Queries) CountHistory(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHistory, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHistory = `-- name: DeleteHistory :exec
DELETE FROM history WHERE id = ?
`

func (q *Queries) DeleteHistory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHistory, id)
	return err
}

const findDuplicate = `-- name: FindDuplicate :one
SELECT id FROM history
WHERE text = ? AND engine_id = ? AND from_lang = ? AND to_lang = ? AND from_ocr = ?
LIMIT 1
`

type FindDuplicateParams struct {
	Text     string `json:"text"`
	EngineID int64  `json:"engine_id"`
	FromLang string `json:"from_lang"`
	ToLang   string `json:"to_lang"`
	FromOcr  int64  `json:"from_ocr"`
}

func (q *Queries) FindDuplicate(ctx context.Context, arg FindDuplicateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findDuplicate,
		arg.Text,
		arg.EngineID,
		arg.FromLang,
		arg.ToLang,
		arg.FromOcr,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertHistory = `-- name: InsertHistory :execlastid
INSERT INTO history (text, result, from_lang, to_lang, engine_id, from_ocr, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertHistoryParams struct {
	Text      string `json:"text"`
	Result    string `json:"result"`
	FromLang  string `json:"from_lang"`
	ToLang    string `json:"to_lang"`
	EngineID  int64  `json:"engine_id"`
	FromOcr   int64  `json:"from_ocr"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertHistory,
		arg.Text,
		arg.Result,
		arg.FromLang,
		arg.ToLang,
		arg.EngineID,
		arg.FromOcr,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const queryHistory = `-- name: QueryHistory :many
SELECT id, text, result, from_lang, to_lang, engine_id, from_ocr, created_at
FROM history
WHERE (?1 = '' OR text LIKE '%' || ?1 || '%' OR result LIKE '%' || ?1 || '%')
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?3
`

type QueryHistoryParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int64       `json:"limit"`
	Offset  int64       `json:"offset"`
}

func (q *Queries) QueryHistory(ctx context.Context, arg QueryHistoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, queryHistory, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Result,
			&i.FromLang,
			&i.ToLang,
			&i.EngineID,
			&i.FromOcr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
