// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Language
} from "./models.js";

export type {
    DictItem,
    OcrRegion,
    OcrRequest,
    OcrResult,
    ScreenshotResult,
    TranslateMultiResult,
    TranslateRequest,
    TranslateResult
} from "./models.js";
