// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DictItem 词典条目
 */
export interface DictItem {
    /**
     * 单词
     */
    "word": string;

    /**
     * 词性（如 n./v.）
     */
    "pos": string;

    /**
     * 释义
     */
    "explain": string;
}

/**
 * Language 语言代码（ISO 639-1 或引擎自定义）
 */
export enum Language {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 翻译语言码（Translate Language）：用于翻译请求/结果、引擎调用、历史记录。
     * 值是翻译引擎约定的短码（如 zh/en/ja），与界面语言完全无关，切勿与下方界面 locale 混用。
     *
     * 自动检测源语言
     */
    Auto = "auto",

    /**
     * 中文
     */
    ZH = "zh",

    /**
     * 英语
     */
    EN = "en",

    /**
     * 日语
     */
    JA = "ja",

    /**
     * 韩语
     */
    KO = "ko",

    /**
     * 法语
     */
    FR = "fr",

    /**
     * 德语
     */
    DE = "de",

    /**
     * 西班牙语
     */
    ES = "es",

    /**
     * 俄语
     */
    RU = "ru",
};

/**
 * OcrRegion 单个文字区域
 */
export interface OcrRegion {
    /**
     * 区域文本
     */
    "text": string;

    /**
     * 识别置信度
     */
    "conf": number;

    /**
     * 区域包围盒坐标 [x1,y1,x2,y2]
     */
    "box": number[] | null;
}

/**
 * OcrRequest OCR 请求
 */
export interface OcrRequest {
    /**
     * 指定 OCR 引擎标识
     */
    "engine": string;

    /**
     * CorrectText Vision 的 usesLanguageCorrection（语言校正）。
     * true=开启（更准确，默认）；false=关闭（更快、偶发卡死概率更低，但准确率略降）。
     * 指针类型以便区分"未设置"与"false"，未设置时引擎用默认值 true。
     */
    "correct_text"?: boolean | null;

    /**
     * TimeoutSec Vision OCR 超时秒数。<=0 时引擎用各自默认值（vision 默认 60s）。
     */
    "timeout_sec"?: number;
}

/**
 * OcrResult OCR 结果
 */
export interface OcrResult {
    /**
     * OCR 引擎标识
     */
    "engine": string;

    /**
     * 识别出的全部文本
     */
    "text": string;

    /**
     * 各文字区域明细
     */
    "regions": OcrRegion[] | null;
}

/**
 * ScreenshotResult 截图翻译完整结果，通过 EventScreenshotOCR 推送到截图窗口。
 */
export interface ScreenshotResult {
    /**
     * 区域截图 PNG 的 base64 data URL（前端直接 <img>）
     */
    "image": string;

    /**
     * OCR 识别出的原文
     */
    "text": string;

    /**
     * 各引擎译文
     */
    "translations": TranslateResult[] | null;

    /**
     * 目标语言
     */
    "to": Language;

    /**
     * 流程失败原因（非空时前端停止转圈并展示错误）
     */
    "error": string;
}

/**
 * TranslateMultiResult 多引擎并行翻译的启动确认，Count 为已启动的引擎数。
 * 实际结果通过事件 EventTranslateResult 逐个流式推送到前端。
 */
export interface TranslateMultiResult {
    /**
     * 已启动的引擎数
     */
    "count": number;

    /**
     * 初始结果集合（含引擎占位）
     */
    "results": TranslateResult[] | null;
}

/**
 * TranslateRequest 统一翻译请求
 */
export interface TranslateRequest {
    /**
     * 待翻译原文
     */
    "text": string;

    /**
     * 源语言（auto 为自动检测）
     */
    "from": Language;

    /**
     * 目标语言
     */
    "to": Language;

    /**
     * 指定翻译引擎标识
     */
    "engine": string;
}

/**
 * TranslateResult 单条翻译结果
 */
export interface TranslateResult {
    /**
     * 翻译引擎标识
     */
    "engine": string;

    /**
     * 实际识别出的源语言
     */
    "from": Language;

    /**
     * 目标语言
     */
    "to": Language;

    /**
     * 原文
     */
    "text": string;

    /**
     * 译文
     */
    "result": string;

    /**
     * 发音/音标
     */
    "phonetic": string;

    /**
     * 词典释义明细
     */
    "dict": DictItem[] | null;

    /**
     * 是否来自 OCR 识别结果
     */
    "from_ocr": boolean;
}
