// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package configstore

type Engine struct {
	ID       int64  `json:"id"`
	Engine   string `json:"engine"`
	Enabled  int64  `json:"enabled"`
	ApiKey   string `json:"api_key"`
	Secret   string `json:"secret"`
	Extra    string `json:"extra"`
	Endpoint string `json:"endpoint"`
}
