// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package configstore

import (
	"context"
)

type Querier interface {
	DeleteEngineByID(ctx context.Context, id int64) error
	GetEngineByID(ctx context.Context, id int64) (Engine, error)
	GetEngineByName(ctx context.Context, engine string) (Engine, error)
	InsertEngine(ctx context.Context, arg InsertEngineParams) (int64, error)
	LoadEngines(ctx context.Context) ([]Engine, error)
	RenameEngineByName(ctx context.Context, arg RenameEngineByNameParams) error
	UpdateEngineByID(ctx context.Context, arg UpdateEngineByIDParams) error
	UpdateEngineEnabled(ctx context.Context, arg UpdateEngineEnabledParams) error
}

var _ Querier = (*Queries)(nil)
