// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package configstore

import (
	"context"
)

const deleteEngineByID = `-- name: DeleteEngineByID :exec
DELETE FROM engines WHERE id = ?
`

func (q *Queries) DeleteEngineByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEngineByID, id)
	return err
}

const getEngineByID = `-- name: GetEngineByID :one
SELECT id, engine, enabled, api_key, secret, extra, endpoint FROM engines WHERE id = ? LIMIT 1
`

func (q *Queries) GetEngineByID(ctx context.Context, id int64) (Engine, error) {
	row := q.db.QueryRowContext(ctx, getEngineByID, id)
	var i Engine
	err := row.Scan(
		&i.ID,
		&i.Engine,
		&i.Enabled,
		&i.ApiKey,
		&i.Secret,
		&i.Extra,
		&i.Endpoint,
	)
	return i, err
}

const getEngineByName = `-- name: GetEngineByName :one
SELECT id, engine, enabled, api_key, secret, extra, endpoint FROM engines WHERE engine = ? LIMIT 1
`

func (q *Queries) GetEngineByName(ctx context.Context, engine string) (Engine, error) {
	row := q.db.QueryRowContext(ctx, getEngineByName, engine)
	var i Engine
	err := row.Scan(
		&i.ID,
		&i.Engine,
		&i.Enabled,
		&i.ApiKey,
		&i.Secret,
		&i.Extra,
		&i.Endpoint,
	)
	return i, err
}

const insertEngine = `-- name: InsertEngine :one
INSERT INTO engines (engine, enabled, api_key, secret, extra, endpoint)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertEngineParams struct {
	Engine   string `json:"engine"`
	Enabled  int64  `json:"enabled"`
	ApiKey   string `json:"api_key"`
	Secret   string `json:"secret"`
	Extra    string `json:"extra"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) InsertEngine(ctx context.Context, arg InsertEngineParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEngine,
		arg.Engine,
		arg.Enabled,
		arg.ApiKey,
		arg.Secret,
		arg.Extra,
		arg.Endpoint,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const loadEngines = `-- name: LoadEngines :many
SELECT id, engine, enabled, api_key, secret, extra, endpoint FROM engines ORDER BY id
`

func (q *Queries) LoadEngines(ctx context.Context) ([]Engine, error) {
	rows, err := q.db.QueryContext(ctx, loadEngines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Engine{}
	for rows.Next() {
		var i Engine
		if err := rows.Scan(
			&i.ID,
			&i.Engine,
			&i.Enabled,
			&i.ApiKey,
			&i.Secret,
			&i.Extra,
			&i.Endpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEngineByID = `-- name: UpdateEngineByID :exec
UPDATE engines SET
    engine   = ?,
    enabled  = ?,
    api_key  = ?,
    secret   = ?,
    extra    = ?,
    endpoint = ?
WHERE id = ?
`

type UpdateEngineByIDParams struct {
	Engine   string `json:"engine"`
	Enabled  int64  `json:"enabled"`
	ApiKey   string `json:"api_key"`
	Secret   string `json:"secret"`
	Extra    string `json:"extra"`
	Endpoint string `json:"endpoint"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateEngineByID(ctx context.Context, arg UpdateEngineByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateEngineByID,
		arg.Engine,
		arg.Enabled,
		arg.ApiKey,
		arg.Secret,
		arg.Extra,
		arg.Endpoint,
		arg.ID,
	)
	return err
}

const updateEngineEnabled = `-- name: UpdateEngineEnabled :exec
UPDATE engines SET enabled = ? WHERE id = ?
`

type UpdateEngineEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) UpdateEngineEnabled(ctx context.Context, arg UpdateEngineEnabledParams) error {
	_, err := q.db.ExecContext(ctx, updateEngineEnabled, arg.Enabled, arg.ID)
	return err
}
