// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineConfig 单个引擎的凭证/配置（唯一来源，settings 包复用此类型，
 * 避免 engine 与 settings 互相 import 造成循环依赖）。
 * ID 为 config.db 主键：0 表示未持久化（前端新增），>0 表示已有行（前端更新/删除以此为依据）。
 * 引擎配置已迁移至 config.db 持久化，不再走 settings.json（故无 mapstructure 标签，仅保留 json 供前端 RPC）。
 */
export interface EngineConfig {
    /**
     * 引擎配置自增主键 ID
     */
    "id": number;

    /**
     * 引擎标识
     */
    "engine": string;

    /**
     * 是否已启用
     */
    "enabled": boolean;

    /**
     * API 令牌 ID（用作鉴权凭据）
     */
    "api_key"?: string;

    /**
     * API 令牌密钥（用作签名密钥）
     */
    "secret"?: string;

    /**
     * 额外扩展配置（JSON 字符串）
     */
    "extra"?: string;

    /**
     * 自定义接口地址（可选）
     */
    "endpoint"?: string;
}

/**
 * EngineFieldSchema 描述某个引擎所需的单个配置字段。
 * Field 对应 EngineConfig 的真实字段名（api_key / secret / endpoint / extra），
 * 这样前端渲染时直接读写对应字段，而不是对所有引擎套用同一套万能表单。
 */
export interface EngineFieldSchema {
    /**
     * 目标字段：api_key / secret / endpoint / extra
     */
    "field": string;

    /**
     * i18n key（前端取 settings.engine_field.<name>）
     */
    "label_key": string;

    /**
     * i18n key（前端取 settings.engine_ph.<name>，可为空）
     */
    "placeholder_key": string;

    /**
     * string / secret
     */
    "type": EngineFieldType;

    /**
     * 启用该引擎时是否必填
     */
    "required": boolean;

    /**
     * 可选 URL/地址等字段的真实默认值，前端在字段为空时预填展示
     */
    "default": string;

    /**
     * 可选枚举值（如 tesseract 语言码 chi_sim/eng）。非空时前端渲染为多选，值以 "+" 拼接写入对应字段
     */
    "options": string[] | null;
}

/**
 * EngineFieldType 配置字段类型（前端据此渲染不同控件）
 */
export enum EngineFieldType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * FieldString 普通文本
     */
    FieldString = "string",

    /**
     * FieldSecret 敏感（密码框）
     */
    FieldSecret = "secret",
};

/**
 * EngineSchema 某个引擎的全部配置字段（顺序即渲染顺序）。
 */
export interface EngineSchema {
    "fields": EngineFieldSchema[] | null;
}
