// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineConfig 单个引擎的凭证/配置（唯一来源，settings 包复用此类型，
 * 避免 engine 与 settings 互相 import 造成循环依赖）。
 * ID 为 config.db 主键：0 表示未持久化（前端新增），>0 表示已有行（前端更新/删除以此为依据）。
 * 引擎配置已迁移至 config.db 持久化，不再走 settings.json（故无 mapstructure 标签，仅保留 json 供前端 RPC）。
 */
export interface EngineConfig {
    /**
     * 引擎配置自增主键 ID
     */
    "id": number;

    /**
     * 引擎标识
     */
    "engine": string;

    /**
     * 是否已启用
     */
    "enabled": boolean;

    /**
     * API 令牌 ID（用作鉴权凭据）
     */
    "api_key"?: string;

    /**
     * API 令牌密钥（用作签名密钥）
     */
    "secret"?: string;

    /**
     * 额外扩展配置（JSON 字符串）
     */
    "extra"?: string;

    /**
     * 自定义接口地址（可选）
     */
    "endpoint"?: string;
}

/**
 * EngineFieldSchema 描述某个引擎所需的单个配置字段。
 * Field 对应 EngineConfig 的真实字段名（api_key / secret / endpoint / extra），
 * 这样前端渲染时直接读写对应字段，而不是对所有引擎套用同一套万能表单。
 */
export interface EngineFieldSchema {
    /**
     * 目标字段：api_key / secret / endpoint / extra
     */
    "field": string;

    /**
     * i18n key（前端取 settings.engine_field.<name>）
     */
    "label_key": string;

    /**
     * i18n key（前端取 settings.engine_ph.<name>，可为空）
     */
    "placeholder_key": string;

    /**
     * string / secret
     */
    "type": EngineFieldType;

    /**
     * 结构化控件覆盖（ocr_*），空则按 Type 渲染
     */
    "widget": FieldWidget;

    /**
     * 启用该引擎时是否必填
     */
    "required": boolean;

    /**
     * 可选 URL/地址等字段的真实默认值，前端在字段为空时预填展示
     */
    "default": string;

    /**
     * 可选枚举值（如 tesseract 语言码 chi_sim/eng）。非空时前端渲染为多选，值以 "+" 拼接写入对应字段
     */
    "options": string[] | null;

    /**
     * 可选：字段下方的说明文案 i18n key
     */
    "hint_key": string;
}

/**
 * EngineFieldType 配置字段类型（前端据此渲染不同控件）
 */
export enum EngineFieldType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * FieldString 普通文本
     */
    FieldString = "string",

    /**
     * FieldSecret 敏感（密码框）
     */
    FieldSecret = "secret",
};

/**
 * EngineKind 引擎种类：翻译 or OCR
 */
export enum EngineKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindTranslator 翻译引擎
     */
    KindTranslator = "translate",

    /**
     * KindOCR OCR 引擎
     */
    KindOCR = "ocr",
};

/**
 * EngineSchema 某个引擎的全部配置字段（顺序即渲染顺序）。
 */
export interface EngineSchema {
    /**
     * Kind 引擎类型（translate 翻译 / ocr OCR），单一事实源；前端据此区分渲染，
     * 取代此前依赖 AllEngineItem.kind 的散落判断。
     */
    "kind": EngineKind;

    /**
     * Builtin 是否为系统内置引擎（如 apple 系统翻译 / vision 系统 OCR），
     * 无需配置、不可移除。前端据此项统一渲染「系统内置」状态卡，取代逐引擎 hardcode 判断。
     */
    "builtin": boolean;

    /**
     * Fields 该引擎在前端配置表单中渲染的字段列表（顺序即渲染顺序）。
     * 每一项对应一个输入框（endpoint / api_key / secret / 语言等），前端据此动态生成表单。
     */
    "fields": EngineFieldSchema[] | null;
}

/**
 * FieldWidget 控件形态覆盖。为空时按 Type 默认渲染（string→文本、secret→密码）；
 * 非空时按此值渲染结构化控件，供 OCR 等引擎复用，使「配置项全部声明于 engineSchemas」。
 */
export enum FieldWidget {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * WidgetOCRLangs OCR 识别语言多选（候选项取 OcrLangsOptions()），值以 "+" 拼写入 Extra.langs
     */
    WidgetOCRLangs = "ocr_langs",

    /**
     * WidgetOCRTimeout OCR 超时（秒），正整数，写入 Extra.timeout_sec
     */
    WidgetOCRTimeout = "ocr_timeout",

    /**
     * WidgetOCRCorrect OCR 语言校正开关，写入 Extra.correct_text（仅 vision 语义生效）
     */
    WidgetOCRCorrect = "ocr_correct",

    /**
     * WidgetOCRRetry Vision OCR 失败兜底重试次数，正整数，写入 Extra.retry_count（仅 vision 语义生效）
     */
    WidgetOCRRetry = "ocr_retry",

    /**
     * WidgetOCRStatus tesseract 安装状态探测卡（含可编辑自定义二进制路径 endpoint），仅 tesseract
     */
    WidgetOCRStatus = "ocr_status",
};

/**
 * TesseractStatus 描述本机 tesseract 的安装探测结果，供前端按系统类型展示安装状态。
 */
export interface TesseractStatus {
    /**
     * 是否探测到 tesseract 可执行文件
     */
    "installed": boolean;

    /**
     * 探测到的可执行路径（未安装则为空）
     */
    "path": string;

    /**
     * 探测到的版本号（未安装则为空），取自 `tesseract --version`
     */
    "version": string;

    /**
     * 当前运行系统（darwin/linux/windows），供前端选择对应安装命令
     */
    "os": string;
}
