// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocaleChangedPayload 界面语言变更事件参数。
 * 注意：这里是界面显示语言，与翻译语言（model.Language：auto/zh/en/...）完全是两套体系，不可混用。
 * Mode 为用户配置的界面语言模式（auto / zh-CN / en-US）；
 * Language 为实际生效的界面语言（zh-CN / en-US，auto 时由系统 locale 派生）。
 */
export interface LocaleChangedPayload {
    /**
     * 界面语言模式：auto | zh-CN | en-US
     */
    "mode": string;

    /**
     * 实际生效界面语言：zh-CN | en-US
     */
    "language": string;
}

/**
 * NotificationPayload 桌面通知事件参数（对齐 certflow）。
 */
export interface NotificationPayload {
    /**
     * 通知标题
     */
    "title": string;

    /**
     * 副标题（如版本号）
     */
    "subtitle": string;

    /**
     * 正文
     */
    "body": string;

    /**
     * 分类：system / cert / deploy ...
     */
    "category": string;

    /**
     * 级别：info | success | warning | error
     */
    "level": string;
}

/**
 * ThemeChangedPayload 主题变更事件参数。
 * Mode 为用户配置模式（取自 model 的 ThemeAuto/ThemeLight/ThemeDark：auto/light/dark）；
 * Theme 为系统真实外观（dark/light，由 Env.IsDarkMode() 派生）。
 */
export interface ThemeChangedPayload {
    /**
     * settings: auto | light | dark
     */
    "mode": string;

    /**
     * settings: dark | light
     */
    "theme": string;
}
