// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationPayload 桌面通知事件参数（对齐 certflow）。
 */
export interface NotificationPayload {
    /**
     * 通知标题
     */
    "title": string;

    /**
     * 副标题（如版本号）
     */
    "subtitle": string;

    /**
     * 正文
     */
    "body": string;

    /**
     * 分类：system / cert / deploy ...
     */
    "category": string;

    /**
     * 级别：info | success | warning | error
     */
    "level": string;
}
