// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * LocaleChangedPayload 界面语言变更事件参数。
 * 注意：这里是界面显示语言，与翻译语言（model.Language：auto/zh/en/...）完全是两套体系，不可混用。
 * Mode 为用户配置的界面语言模式（auto / zh-CN / en-US）；
 * Language 为实际生效的界面语言（zh-CN / en-US，auto 时由系统 locale 派生）。
 */
export interface LocaleChangedPayload {
    /**
     * 界面语言模式：auto | zh-CN | en-US
     */
    "mode": string;

    /**
     * 实际生效界面语言：zh-CN | en-US
     */
    "language": string;
}

/**
 * ScreenshotRetranslatePayload 截图翻译改语言重新翻译事件参数。
 * Session 标识缓存来源（ScreenshotSessionScreenshot / ScreenshotSessionInput），
 * 后端据此取用对应入口最近一次 OCR 原文，避免不同入口互相串。
 * From/To 为目标翻译语言组合（From 允许 Auto），后端复用最近一次 OCR 原文重新翻译。
 */
export interface ScreenshotRetranslatePayload {
    "session": string;
    "from": model$0.Language;
    "to": model$0.Language;
}

/**
 * ThemeChangedPayload 主题变更事件参数。
 * Mode 为用户配置模式（取自 model 的 ThemeAuto/ThemeLight/ThemeDark：auto/light/dark）；
 * Theme 为系统真实外观（dark/light，由 Env.IsDarkMode() 派生）。
 */
export interface ThemeChangedPayload {
    /**
     * settings: auto | light | dark
     */
    "mode": string;

    /**
     * settings: dark | light
     */
    "theme": string;
}
